// Phường/xã của Hà Nội và TP.HCM theo đơn vị hành chính mới (bỏ cấp quận/huyện từ 01/07/2025)
// Nguồn: provinces.open-api.vn (API v2). Hà Nội: 126, TP.HCM: 168 phường/xã/đặc khu
export const CITIES = [
    {
        name: "Thành phố Hà Nội",
        wards: [
            "Xã An Khánh",
            "Phường Ba Đình",
            "Xã Ba Vì",
            "Phường Bạch Mai",
            "Xã Bát Tràng",
            "Xã Bất Bạt",
            "Xã Bình Minh",
            "Phường Bồ Đề",
            "Phường Cầu Giấy",
            "Xã Chuyên Mỹ",
            "Xã Chương Dương",
            "Phường Chương Mỹ",
            "Xã Cổ Đô",
            "Phường Cửa Nam",
            "Xã Dân Hòa",
            "Xã Dương Hòa",
            "Phường Dương Nội",
            "Xã Đa Phúc",
            "Phường Đại Mỗ",
            "Xã Đại Thanh",
            "Xã Đại Xuyên",
            "Xã Đan Phượng",
            "Phường Định Công",
            "Xã Đoài Phương",
            "Xã Đông Anh",
            "Phường Đống Đa",
            "Phường Đông Ngạc",
            "Xã Gia Lâm",
            "Phường Giảng Võ",
            "Xã Hạ Bằng",
            "Phường Hà Đông",
            "Phường Hai Bà Trưng",
            "Xã Hát Môn",
            "Xã Hòa Lạc",
            "Xã Hòa Phú",
            "Xã Hòa Xá",
            "Xã Hoài Đức",
            "Phường Hoàn Kiếm",
            "Phường Hoàng Liệt",
            "Phường Hoàng Mai",
            "Phường Hồng Hà",
            "Xã Hồng Sơn",
            "Xã Hồng Vân",
            "Xã Hưng Đạo",
            "Xã Hương Sơn",
            "Phường Khương Đình",
            "Phường Kiến Hưng",
            "Xã Kiều Phú",
            "Xã Kim Anh",
            "Phường Kim Liên",
            "Phường Láng",
            "Xã Liên Minh",
            "Phường Lĩnh Nam",
            "Phường Long Biên",
            "Xã Mê Linh",
            "Xã Minh Châu",
            "Xã Mỹ Đức",
            "Xã Nam Phù",
            "Phường Nghĩa Đô",
            "Phường Ngọc Hà",
            "Xã Ngọc Hồi",
            "Xã Nội Bài",
            "Phường Ô Chợ Dừa",
            "Xã Ô Diên",
            "Xã Phú Cát",
            "Phường Phú Diễn",
            "Xã Phù Đổng",
            "Phường Phú Lương",
            "Xã Phú Nghĩa",
            "Phường Phú Thượng",
            "Xã Phú Xuyên",
            "Xã Phúc Lộc",
            "Phường Phúc Lợi",
            "Xã Phúc Sơn",
            "Xã Phúc Thịnh",
            "Xã Phúc Thọ",
            "Xã Phượng Dực",
            "Phường Phương Liệt",
            "Xã Quảng Bị",
            "Xã Quang Minh",
            "Xã Quảng Oai",
            "Xã Quốc Oai",
            "Xã Sóc Sơn",
            "Xã Sơn Đồng",
            "Phường Sơn Tây",
            "Xã Suối Hai",
            "Xã Tam Hưng",
            "Phường Tây Hồ",
            "Phường Tây Mỗ",
            "Xã Tây Phương",
            "Phường Tây Tựu",
            "Xã Thạch Thất",
            "Phường Thanh Liệt",
            "Xã Thanh Oai",
            "Xã Thanh Trì",
            "Phường Thanh Xuân",
            "Xã Thiên Lộc",
            "Xã Thuận An",
            "Xã Thư Lâm",
            "Phường Thượng Cát",
            "Xã Thượng Phúc",
            "Xã Thường Tín",
            "Xã Tiến Thắng",
            "Xã Trần Phú",
            "Xã Trung Giã",
            "Phường Tùng Thiện",
            "Phường Từ Liêm",
            "Phường Tương Mai",
            "Xã Ứng Hòa",
            "Xã Ứng Thiên",
            "Phường Văn Miếu - Quốc Tử Giám",
            "Xã Vân Đình",
            "Xã Vật Lại",
            "Phường Việt Hưng",
            "Phường Vĩnh Hưng",
            "Xã Vĩnh Thanh",
            "Phường Vĩnh Tuy",
            "Phường Xuân Đỉnh",
            "Xã Xuân Mai",
            "Phường Xuân Phương",
            "Xã Yên Bài",
            "Phường Yên Hòa",
            "Xã Yên Lãng",
            "Phường Yên Nghĩa",
            "Phường Yên Sở",
            "Xã Yên Xuân"
        ]
    },
    {
        name: "Thành phố Hồ Chí Minh",
        wards: [
            "Phường An Đông",
            "Phường An Hội Đông",
            "Phường An Hội Tây",
            "Phường An Khánh",
            "Phường An Lạc",
            "Xã An Long",
            "Phường An Nhơn",
            "Xã An Nhơn Tây",
            "Phường An Phú",
            "Phường An Phú Đông",
            "Xã An Thới Đông",
            "Xã Bà Điểm",
            "Phường Bà Rịa",
            "Phường Bàn Cờ",
            "Xã Bàu Bàng",
            "Xã Bàu Lâm",
            "Phường Bảy Hiền",
            "Xã Bắc Tân Uyên",
            "Phường Bến Cát",
            "Phường Bến Thành",
            "Xã Bình Chánh",
            "Xã Bình Châu",
            "Phường Bình Cơ",
            "Phường Bình Dương",
            "Phường Bình Đông",
            "Xã Bình Giã",
            "Phường Bình Hòa",
            "Xã Bình Hưng",
            "Phường Bình Hưng Hòa",
            "Xã Bình Khánh",
            "Xã Bình Lợi",
            "Phường Bình Lợi Trung",
            "Xã Bình Mỹ",
            "Phường Bình Phú",
            "Phường Bình Quới",
            "Phường Bình Tân",
            "Phường Bình Tây",
            "Phường Bình Thạnh",
            "Phường Bình Thới",
            "Phường Bình Tiên",
            "Phường Bình Trị Đông",
            "Phường Bình Trưng",
            "Phường Cát Lái",
            "Xã Cần Giờ",
            "Phường Cầu Kiệu",
            "Phường Cầu Ông Lãnh",
            "Phường Chánh Hiệp",
            "Phường Chánh Hưng",
            "Phường Chánh Phú Hòa",
            "Xã Châu Đức",
            "Xã Châu Pha",
            "Phường Chợ Lớn",
            "Phường Chợ Quán",
            "Đặc khu Côn Đảo",
            "Xã Củ Chi",
            "Xã Dầu Tiếng",
            "Phường Dĩ An",
            "Phường Diên Hồng",
            "Xã Đất Đỏ",
            "Phường Đông Hòa",
            "Phường Đông Hưng Thuận",
            "Xã Đông Thạnh",
            "Phường Đức Nhuận",
            "Phường Gia Định",
            "Phường Gò Vấp",
            "Phường Hạnh Thông",
            "Phường Hiệp Bình",
            "Xã Hiệp Phước",
            "Phường Hòa Bình",
            "Xã Hòa Hiệp",
            "Xã Hòa Hội",
            "Phường Hòa Hưng",
            "Phường Hòa Lợi",
            "Xã Hóc Môn",
            "Xã Hồ Tràm",
            "Xã Hưng Long",
            "Phường Khánh Hội",
            "Xã Kim Long",
            "Phường Lái Thiêu",
            "Phường Linh Xuân",
            "Phường Long Bình",
            "Xã Long Điền",
            "Xã Long Hải",
            "Xã Long Hòa",
            "Phường Long Hương",
            "Phường Long Nguyên",
            "Phường Long Phước",
            "Xã Long Sơn",
            "Phường Long Trường",
            "Phường Minh Phụng",
            "Xã Minh Thạnh",
            "Xã Ngãi Giao",
            "Xã Nghĩa Thành",
            "Xã Nhà Bè",
            "Phường Nhiêu Lộc",
            "Xã Nhuận Đức",
            "Phường Phú An",
            "Phường Phú Định",
            "Xã Phú Giáo",
            "Xã Phú Hòa Đông",
            "Phường Phú Lâm",
            "Phường Phú Lợi",
            "Phường Phú Mỹ",
            "Phường Phú Nhuận",
            "Phường Phú Thạnh",
            "Phường Phú Thọ",
            "Phường Phú Thọ Hòa",
            "Phường Phú Thuận",
            "Xã Phước Hải",
            "Xã Phước Hòa",
            "Phường Phước Long",
            "Xã Phước Thành",
            "Phường Phước Thắng",
            "Phường Rạch Dừa",
            "Phường Sài Gòn",
            "Phường Tam Bình",
            "Phường Tam Long",
            "Phường Tam Thắng",
            "Phường Tăng Nhơn Phú",
            "Xã Tân An Hội",
            "Phường Tân Bình",
            "Phường Tân Định",
            "Phường Tân Đông Hiệp",
            "Phường Tân Hải",
            "Phường Tân Hiệp",
            "Phường Tân Hòa",
            "Phường Tân Hưng",
            "Phường Tân Khánh",
            "Phường Tân Mỹ",
            "Xã Tân Nhựt",
            "Phường Tân Phú",
            "Phường Tân Phước",
            "Phường Tân Sơn",
            "Phường Tân Sơn Hòa",
            "Phường Tân Sơn Nhất",
            "Phường Tân Sơn Nhì",
            "Phường Tân Tạo",
            "Phường Tân Thành",
            "Phường Tân Thới Hiệp",
            "Phường Tân Thuận",
            "Phường Tân Uyên",
            "Xã Tân Vĩnh Lộc",
            "Phường Tây Nam",
            "Phường Tây Thạnh",
            "Xã Thái Mỹ",
            "Xã Thanh An",
            "Xã Thạnh An",
            "Phường Thạnh Mỹ Tây",
            "Phường Thông Tây Hội",
            "Phường Thới An",
            "Phường Thới Hòa",
            "Phường Thủ Dầu Một",
            "Phường Thủ Đức",
            "Phường Thuận An",
            "Phường Thuận Giao",
            "Xã Thường Tân",
            "Phường Trung Mỹ Tây",
            "Xã Trừ Văn Thố",
            "Phường Vĩnh Hội",
            "Xã Vĩnh Lộc",
            "Phường Vĩnh Tân",
            "Phường Vũng Tàu",
            "Phường Vườn Lài",
            "Phường Xóm Chiếu",
            "Phường Xuân Hòa",
            "Xã Xuân Sơn",
            "Xã Xuân Thới Sơn",
            "Xã Xuyên Mộc"
        ]
    }
];
